import { defineManifest } from '@crxjs/vite-plugin'

/**
 * MV3 manifest.
 *
 * ## Why two content scripts instead of `chrome.webRequest`
 *
 * MV3 offers no way to read a response *body* from an extension API:
 * `webRequest` exposes headers only, `declarativeNetRequest` cannot observe at
 * all, and `chrome.debugger` would attach a "being debugged" banner to the tab
 * and lock out DevTools. The only remaining seam is the page's own network
 * primitives, so this extension patches `fetch` / `XMLHttpRequest` /
 * `EventSource` inside the page.
 *
 * That forces both properties declared below:
 *
 * - `world: 'MAIN'` — the patch has to replace the same `window.fetch` the page
 *   scripts will call. An ISOLATED content script has a private global object,
 *   so patching there is invisible to the page.
 * - `run_at: 'document_start'` — a page script that captures `const f = fetch`
 *   before we patch keeps the original forever. Injecting on user action (via
 *   `chrome.scripting.executeScript` when the panel opens) is therefore too
 *   late and silently misses streams.
 *
 * The MAIN world cannot touch `chrome.runtime`, so a second ISOLATED script
 * relays messages between the page and the service worker. Both must be
 * `all_frames` because a stream is often opened by an embedded iframe.
 *
 * ## Permissions, each load-bearing
 *
 * - `storage`: settings in `chrome.storage.local`; captured stream data in
 *   `chrome.storage.session`, which never touches disk (a capture may contain
 *   an auth token, so it must not outlive the browser session).
 * - `tabs`: capture is scoped to the *current* tab, which means resolving the
 *   active tab and following activation/navigation events.
 * - `sidePanel`: the reader lives in a side panel so it survives focus changes
 *   and can sit beside the page under observation, unlike a popup.
 *
 * Deliberately NOT requested: `webRequest` (cannot read bodies — see above),
 * `debugger`, `scripting` (nothing is injected on demand; both scripts are
 * static), and `unlimitedStorage` (captures are quota-trimmed and session-only).
 *
 * `host_permissions` is broad because a capture target can be any http(s)
 * origin; the URL filter in Settings narrows what is actually recorded.
 *
 * Icon paths are `icons/…`, not `public/icons/…`: Vite copies the *contents* of
 * `public/` to the bundle root, so the directory name is not part of the shipped
 * path. Generated by `scripts/generate-icons.mjs`.
 */
export default defineManifest({
  manifest_version: 3,
  name: 'SSE Lens',
  version: '0.1.0',
  description:
    "Inspect the current tab's Server-Sent Events and streaming responses: framed events, JSON trees, merged LLM deltas, and raw text.",
  // `world: 'MAIN'` in a static content script requires Chrome 111; the side
  // panel API requires 114. 116 matches the rest of this toolchain.
  minimum_chrome_version: '116',
  permissions: ['storage', 'tabs', 'sidePanel'],
  host_permissions: ['http://*/*', 'https://*/*'],
  icons: {
    16: 'icons/icon-16.png',
    32: 'icons/icon-32.png',
    48: 'icons/icon-48.png',
    128: 'icons/icon-128.png',
  },
  background: {
    service_worker: 'src/background/index.ts',
    type: 'module',
  },
  action: {
    default_title: 'Open SSE Lens',
    default_icon: {
      16: 'icons/icon-16.png',
      32: 'icons/icon-32.png',
      48: 'icons/icon-48.png',
      128: 'icons/icon-128.png',
    },
  },
  side_panel: {
    default_path: 'src/panel/index.html',
  },
  content_scripts: [
    {
      matches: ['http://*/*', 'https://*/*'],
      js: ['src/inpage/hook.ts'],
      run_at: 'document_start',
      world: 'MAIN',
      all_frames: true,
    },
    {
      matches: ['http://*/*', 'https://*/*'],
      js: ['src/content/relay.ts'],
      run_at: 'document_start',
      world: 'ISOLATED',
      all_frames: true,
    },
  ],
})
